### ISSUE TITLE
can't delete chat

### ISSUE THREAD

**Issue by kr-nahid** [chat21/chat21-android-demo#13]
#### Expected behavior
it should be delete chat when click on delete

#### Actual behavior
when click on delete it can't able to delete chats

#### How to reproduce
* download the app and run it
* scroll on Home button and select a contact
* then come to Chat sector
* and try to delete a chat 

> Browser/App version: **chat21** 1.0.9
 Operating system: android 6.0

#### Recording Of The Bug
https://www.youtube.com/watch?v=CZBrdhiWGR4

**Comment by stefanodp91** [comment]
Hi Nahid,
Thanks for contacting Chat21 SDK Support. 
This is an high priority bug that will be fixed in the next Chat21 SDK release.
Stay tuned

**Comment by stefanodp91** [comment]
Solved within the v. 1.0.10 of the Chat21 Android SDK

More details here:
https://github.com/chat21/chat21-android-sdk/commit/f30993ac9f72faf8d9d8409665f68f4cab448476
