### ISSUE TITLE
App stop working when I try to login

### ISSUE THREAD

**Issue by esmondgh** [chat21/chat21-android-demo#20]
The Chat21 Cloud Functions setup was successful.
When I use my "google-services" .json file in App and try to login, App stop working.
When I use your "google-services" .json file in App, Login is successful.

![chat21_stop](https://user-images.githubusercontent.com/42568091/44624452-164f2f00-a8e7-11e8-9477-76ccc2c1a022.png)

**Comment by venkatthesaiyan** [comment]
Same problem.did it solved ?

**Comment by giovankabisano** [comment]
The firebase service for this project is already full. You need to make your own firebase database and change the google-service.json with your own

**Comment by sharjeel-ayubi** [comment]
-Create your own firebase project 
-In Project Settings, add your app and turn email verification on from Authentication panel.
-Create realtime database, cloud functions and storage bucket. Get 3 separate URLs after setting up these database, functions and storage.
-Replace these URL in chat_settings.xml under the tags of chat_firebase_url, chat_firebase_cloud_functions_url and chat_firebase_storage_bucket.
-Copy the app ID from project settings where you added your app and replace it in chat_settings.xml under chat_firebase_appId tag.
P.S use your own created google-services.json.

**Comment by SimiPam** [comment]
Pls how/where do i create the cloud function?
