### ISSUE TITLE
Failed to resolve dependencies: Chat 21 Demo

### ISSUE THREAD

**Issue by tobimichigan** [chat21/chat21-android-demo#24]
Hi there. Please could help look into whu these bugs keep coming out on first run after cloning and importing this repo for testing purposes? I have ran the cloud functions as instructed and set up my firebase.
"
Failed to resolve: firebase-iid
Open File
Failed to resolve: firebase-common
Open File
Failed to resolve: firebase-messaging-license
Open File
Failed to resolve: play-services-tasks-license
Open File
Failed to resolve: play-services
Open File
Failed to resolve: play-services-auth
Open File
Failed to resolve: play-services-drive
Open File
Failed to resolve: play-services-identity
Open File
Failed to resolve: play-services-plus
Open File
Failed to resolve: firebase-iid
Open File
Failed to resolve: firebase-common
Open File
Failed to resolve: play-services-auth-base-license
Open File
Failed to resolve: firebase-messaging-license
Open File
Failed to resolve: play-services-tasks-license
Open File

"

**Comment by rohitslayer** [comment]
Invalidate caches and restart
